language: objective-c
osx_image: xcode10.1
xcode_project: FineDust.xcworkspace
xcode_scheme: FineDust, FineDustTests
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
notifications:
  slack:
    secure: QIiXML90MYjctagBcoMYMo8v0s/z9Rv6EY3Krdjb+QhTQ+/56iL5aMQ/ymVcX2WOmnj8j3OzsDU31v2jbDRJFOnlfUXmMUQi+TZILDwPbhc/mbTajA7PCxEEYapfZhVeM6rJCevDJFqD1TSTRHc0oW/1hxPi/ZdQGw5xHq8t/myNXwJT6ZK3bF4o+LMU/jkYAMSzFS0p9U3aT2VdbnyEN5JnTIOnyeQaN2eIqUTa+1/eLmu1CgsVawUx5yhh1lp1Z9/lXFSw1p8sfp3yiP3m+pNY3u8K9NUK6b6wUrt0R0vp3mOxRmsajZgo+CHT4axfd4+VTCAQG8NtCPNXI74VHkHpUeHuLjNYLm1Nrkf49vNYwTaKSw1PcWK2/R2hRMznCXOkud++5symbi1MvTEucv0Sc+T0Ty1GZeHdzX3wdKTXMW0gilnfJ2+sS1ertz4nwX6p/lK4k7gI9PLbBFH1uZ/ZQmFDyYzdYg4FNrYU9d45oKakL6hi3vipZ0vT7AyG/qqd9hhlVIaxXCSJmo7OfvsohZH+qaCRpTV8IPgYcEKa3IJnyH4GUjYAUAcG7Pw7yp4sxK09lhXUpbqKq01bammrqcVf/baLb1ZdrltZoAlOuj2jIMguGEOpVlZ9qb+4af3Rminkyow1k7etmwqO7MovSNQKy1etFGgU+uv/1Bo=
before_install:
  - rvm use system
  - sudo gem install cocoapods --pre
